#!/usr/bin/env python
#
#
#

import argparse

def print_variant_stats(vcf_file):
    print("#variant_details\t" + vcf_file)
    print("Chrom\tPos\tID\tREF\tALT\tQUAL\tFILTER\tAF\tAC")
    with open(vcf_file) as f:
        for line in f:
            if "#" in line:
                continue
            line = line.split('\t')
            info_field = line[7].split(';')
            chrom = line[0]
            pos = line[1]
            id = line[2]
            ref = line[3]
            alt = line[4]
            qual = line[5]
            filter = line[6]
            
